# Intro to tensorflow 

A quick recap and intro to Tensorflow.

In [ ]:
# import the necessary libraries 
import tensorflow as tf
import numpy as np 
import pandas as pd


print(tf.__version__)

2.6.0


In [ ]:
# create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimension of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# cerat a vector 
vector=tf.constant([10,10])
# check the dimension of the vector 
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# creat  a matrix with more than one dimension 
meatrix=tf.constant([[10,10],[12,12]])
meatrix.ndim

2

In [ ]:
# lets create a tensor 
tensor=tf.constant([[[1,2],
                     [1,2]],
                    [[3,4],
                     [3,4]]
                   ])
tensor.ndim

3

Recap 
* Scalar: 0 dimensional or single number 
* Vector: A number with a direction
* Matrix: a 2 dimensional vector 
* Tensor: an n-dimensional array of numbers 

In [ ]:
# Creating tensors with 'tf.variable'

In [ ]:
# tf variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# lets try and change one of the elements using .assign  
changeable_tensor[0].assign(7)
# lets try the same on the unchangeable tensor
#unchangeable_tensor[0].assign(0)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Lets create random tensor

In [ ]:
# Lets create random tensor
random_1=tf.random.Generator.from_seed(123) # use the seed to repeat the randomness
random_1=random_1.normal(shape=(3,2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.8673864 , -0.29899067],
       [-0.93103355, -1.5828488 ],
       [ 1.2481192 , -0.67706424]], dtype=float32)>

In [ ]:
random_2=tf.random.Generator.from_seed(123)
random_2=random_2.uniform(shape=(3,2))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.8673864 , -0.29899067],
        [-0.93103355, -1.5828488 ],
        [ 1.2481192 , -0.67706424]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.65647066, 0.30283117],
        [0.18523741, 0.5846225 ],
        [0.36490846, 0.3291067 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# Tensor order shuffle 

In [ ]:
# Lets shuffle the order of tensors (When we want to shuffle our data so that the neural network doesnt affect the learning )

not_shuffled=tf.constant([[1,2],[3,4],[4,5]])
not_shuffled.ndim

# shuffle our non shuffled tensor 

shuffled_tensor=tf.random.shuffle(not_shuffled,seed=1213)
# we can see that it is shuffling along the first dimension
not_shuffled,shuffled_tensor

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [4, 5],
        [1, 2]], dtype=int32)>)

In [ ]:
#  # The difference between the global and the local random seed 
# If we want the shuffle to be consistent then we might want to use the global and local level random seed

tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]], dtype=int32)>

In [ ]:
# Other way to make tensors

# create a tensor to make a matrix of all 1

tf.ones([10,7])
tf.zeros(shape=[10,7])


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Numpy into Tensors 

The main difference between the numpy and the tensor values is that tensors are optimized for GPU performance.


In [ ]:
numpy_A=[[1,2,3],[12,23,43],[56,67,45]]
numpy_B=np.arange(1,25,dtype=np.int32)
x=tf.constant(numpy_A)# Always the scalar is capital and the vactor is small 
tf.random.shuffle(x)
y=tf.constant(numpy_B,shape=(2,3,4))
y

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting info from our tensors 

* Shape : The length of each of the dimensions of a tensor 
* Axis or dimesnion : A particular dimension of a tensor 
* Rank : The number of tensor dimensions.
* Size : the total numnber of items in the tensor

In [ ]:
# Getting info from our tensors 

# Create a rank 4 dimension tensor 

rank_4_tensor= tf.constant(np.arange(1,5),shape=(4,1,1,1))
rank_4_tensor= tf.zeros(shape=(2,3,4,5))

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get all the 4 info 
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor),rank_4_tensor.dtype
print('The number of elements in a array', tf.size(rank_4_tensor).numpy())# returns the exact size 
print('The number of elements in a tensor', tf.size(rank_4_tensor))

The number of elements in a array 120
The number of elements in a tensor tf.Tensor(120, shape=(), dtype=int32)


# Indexing Tensors

Tensors can be indexed similar to a python lists


In [ ]:
# get the first 2 elements of a tensor


random_gen=tf.random.Generator.from_seed(42)
tensor_index=random_gen.normal(shape=(2,3,4,5))
tensor_index[:2,:2,:2],tensor_index[0,2]

(<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
 array([[[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ,
           -0.23193765],
          [-1.8107855 ,  0.09988727, -0.50998646, -0.7535806 ,
           -0.5716629 ]],
 
         [[-0.08763231, -0.635568  , -0.6161736 , -1.9441465 ,
           -0.48293006],
          [-0.5244748 , -1.0345329 ,  1.3066901 , -1.5184573 ,
           -0.4585211 ]]],
 
 
        [[[ 0.49689844,  0.8259971 ,  1.0340209 , -0.24918638,
           -1.5780283 ],
          [-0.92161775,  0.268676  ,  0.9418312 , -0.9465717 ,
           -0.7108357 ]],
 
         [[-2.5255601 ,  0.05080947,  1.7212061 , -0.6575124 ,
            0.7939443 ],
          [ 1.3212339 ,  0.34584793, -0.6699328 ,  0.4604257 ,
            0.514933  ]]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[ 1.0034493 ,  0.20857747,  0.35700995,  1.0648885 ,  1.2432486 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ,  0.01380118, -0.24827152],
        [ 

In [ ]:
# get the first element from each dimension except for the final one 
tensor_index[:1,:,:1,:1],tensor_index
# Add extra diemension for the tensor 
# method 1
tensor_index[...,tf.newaxis]
# Method 2
tf.expand_dims(tensor_index,axis=-1)

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[-0.7565803 ],
          [-0.06854702],
          [ 0.07595026],
          [-1.2573844 ],
          [-0.23193765]],

         [[-1.8107855 ],
          [ 0.09988727],
          [-0.50998646],
          [-0.7535806 ],
          [-0.5716629 ]],

         [[ 0.1480774 ],
          [-0.23362991],
          [-0.3522796 ],
          [ 0.40621266],
          [-1.0523509 ]],

         [[ 1.2054597 ],
          [ 1.6874489 ],
          [-0.44629744],
          [-2.3410842 ],
          [ 0.99009085]]],


        [[[-0.08763231],
          [-0.635568  ],
          [-0.6161736 ],
          [-1.9441465 ],
          [-0.48293006]],

         [[-0.5244748 ],
          [-1.0345329 ],
          [ 1.3066901 ],
          [-1.5184573 ],
          [-0.4585211 ]],

         [[ 0.5714663 ],
          [-1.5331722 ],
          [ 0.45331386],
          [ 1.1487608 ],
          [-1.2659091 ]],

         [[-0.47450137],
          [ 2.006022  ],
  

## manipulating Tensors 

** Basic operations **
* Addition operation
* Subtraction operation
* Multiply operation 
* Division operation 

In [ ]:
# Manipulating tensors basic operations 
tensor_2_dim= tf.ones(shape=(2,2))
tensor_2_dim+10,tensor_2_dim*10,tensor_2_dim-10,tensor_2_dim/10

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[11., 11.],
        [11., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[10., 10.],
        [10., 10.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-9., -9.],
        [-9., -9.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32)>)

In [ ]:
# In addition to these we can also use tensorflow built-in fucntion ( This is very much useful when you want to use the GPU for it)
tf.multiply(tensor_2_dim,10),tf.add(tensor_2_dim,10),tf.subtract(tensor_2_dim,10),tf.divide(tensor_2_dim,19),tensor_2_dim
# even though all the operations were performed, the actual value of the tensor wasnt changed. 

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[10., 10.],
        [10., 10.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[11., 11.],
        [11., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-9., -9.],
        [-9., -9.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.05263158, 0.05263158],
        [0.05263158, 0.05263158]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>)

In [ ]:
# Matrix multiplication (Pretty important operations that are to be folowed), Other operation mentioned above are elementwise operations 
tensor=tf.constant(tensor,shape=(2,4))
print(tensor)
tf.matmul(tensor,tf.transpose(tensor))

tf.Tensor(
[[1 2 1 2]
 [3 4 3 4]], shape=(2, 4), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 22],
       [22, 50]], dtype=int32)>

In [ ]:
# Python has an internal operator for matmul 
tensor @ tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 22],
       [22, 50]], dtype=int32)>

In [ ]:
# how to multiply matrices of different shape
x=tf.constant([[1,2]
              ,[3,4],
               [4,5]])

y=tf.constant([[34,56],
               [23,34],
               [23,56]])

# instead of transpose can one also do the reshape? 

x@tf.transpose(y),x@tf.reshape(y,shape=(2,3)) # apprantely the answer is no 


(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[146,  91, 135],
        [326, 205, 293],
        [416, 262, 372]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[102, 102, 135],
        [238, 260, 293],
        [306, 339, 372]], dtype=int32)>)

In [ ]:
x,tf.reshape(x,shape=(2,3)),tf.transpose(x)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 4, 5]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 4],
        [2, 4, 5]], dtype=int32)>)

# The dot product 

Matrix multiplication is also referenced to as the dot product.

You can perform the matrix multiplication using:

* tf.matmul()
* tf.tensordot()

In [ ]:
# Perform the dot product on x and y , the x or y should be transposed and not reshaped.
tf.tensordot(tf.transpose(x),y,axes=1)# In the tensordot fucntion axes is compulsory

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[195, 382],
       [275, 528]], dtype=int32)>

# Changing the Default datatype of the tensor 

 We dont get to work with the same datatype all the time, so , we might have to change them. 
 

In [ ]:
# Create a new tensor with the default datatype

gen_rand= tf.random.Generator.from_seed(42)
x=gen_rand.normal(shape=(3,2))
y=tf.constant([[1,2],[3,4],[3,4]])
x,y
# The default datatype is either the float or int 32, but we can reduce the precision 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [3, 4]], dtype=int32)>)

In [ ]:
# how to change it from 32 to 16
x=tf.cast(x,dtype=tf.float16)
x,tf.cast(y,dtype=tf.int16)

(<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
 array([[-0.7563 , -0.06854],
        [ 0.0759 , -1.258  ],
        [-0.2319 , -1.811  ]], dtype=float16)>,
 <tf.Tensor: shape=(3, 2), dtype=int16, numpy=
 array([[1, 2],
        [3, 4],
        [3, 4]], dtype=int16)>)

# Aggregation of tensors 
 the general definition of aggregation is to condense multiple values down to a smaller amount of values.

* Absolute 
* min 
* max
* mean
* Sum 



In [ ]:
# get the absolute value 
D=tf.constant([-1,-20])

tf.abs(D)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 20], dtype=int32)>

In [ ]:
E=tf.constant(np.random.randint(0,100,size=50))
E=tf.reshape(E,shape=(2,25))

# Find the min of the tensor 
E, tf.reduce_min(E),tf.reduce_max(E),tf.reduce_mean(E),tf.reduce_sum(E)

(<tf.Tensor: shape=(2, 25), dtype=int64, numpy=
 array([[59, 23,  0, 49, 26, 33,  9, 86, 12, 10, 48,  8, 70, 63, 57, 98,
         92,  0, 33, 82, 48, 18, 55, 22, 86],
        [62,  5, 49, 84, 69, 21, 54, 87, 68, 71, 50, 60, 19, 39, 47, 14,
         75, 23, 80, 67, 63, 45, 42, 21, 72]])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>,
 <tf.Tensor: shape=(), dtype=int64, numpy=98>,
 <tf.Tensor: shape=(), dtype=int64, numpy=47>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2374>)

In [ ]:
# To find the variance 
import tensorflow_probability as tfp 
E=tf.cast(E,dtype=float)

tf.math.reduce_std(E),tf.math.reduce_variance(E),tf.math.reduce_std(E).numpy()**2


(<tf.Tensor: shape=(), dtype=float32, numpy=27.044586>,
 <tf.Tensor: shape=(), dtype=float32, numpy=731.4096>,
 731.409641736187)

In [ ]:
# To find the positional max and minimum 

tf.math.argmax(E),tf.math.argmin(E)
# index it along the matrix 



(<tf.Tensor: shape=(25,), dtype=int64, numpy=
 array([1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        0, 0, 0])>, <tf.Tensor: shape=(25,), dtype=int64, numpy=
 array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 1])>)

# Squeezing a Tensor (removing all single dimensions)



In [ ]:
# create a dummy tensor 
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50,1))
G.shape

TensorShape([1, 1, 1, 50, 1])

In [ ]:
g_squeezed=tf.squeeze(G)
g_squeezed,g_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

# One-hot Encoding tensors 

In [ ]:
# CREATE A LIST OF INDICES 
list_index=[1,2,3]

# one hot encode our list of indices 

tf.one_hot(list_index,depth=len(list_index)+1)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Squaring , log, square_root





In [ ]:
# create a new tensor 

H=tf.range(0,10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it ,square root, log 
tf.square(H) ,tf.math.sqrt(tf.cast(H,dtype=tf.float16)),tf.math.log(tf.cast(H,dtype=tf.float16))

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(10,), dtype=float16, numpy=
 array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
        3.   ], dtype=float16)>,
 <tf.Tensor: shape=(10,), dtype=float16, numpy=
 array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
        2.08  , 2.197 ], dtype=float16)>)

# Tensors and numpy 

In [ ]:
# Create a tensor directly fom numpy and vice versa 

j=tf.constant(np.array([2,3,4]))
j,np.array(j)

(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 3, 4])>,
 array([2, 3, 4]))

In [ ]:
# the default datatype for the tensor and the numpy are slightly different 
numpy_j=tf.constant(np.array([1.0,2,3]))
tensor_j=tf.constant([1.0,2,3])
numpy_j.dtype,tensor_j.dtype


(tf.float64, tf.float32)

# Find access to the GPUs 


In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Aug 30 00:53:14 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P0    60W / 149W |    123MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# If we have access to a CUDA enabled GPU tensorflow will run it whenever possible

# Exercise 

In [ ]:
# create a vector, scalar , matric and a tensor using tf.constant 

scalar=tf.constant(0)

vector= tf.constant([1,2,3])

matrix=tf.constant(tf.random.normal(shape=(3,3),mean=10))

tensor=tf.constant(tf.random.uniform(shape=(3,4,5)))

scalar.ndim,vector.ndim, matrix.ndim,tensor.ndim

(0, 1, 2, 3)

In [ ]:
# Find the shape rank and size for the tensors in 1


for x in [scalar,vector,matrix,tensor]:
  print(tf.size(x).numpy(),x.shape,x.ndim)


1 () 0
3 (3,) 1
9 (3, 3) 2
60 (3, 4, 5) 3


In [ ]:
# Create 2 tensors with random value belween 0 and 1 with the shape [5,300]
tf.random.Generator.from_seed(42)
# using tensor random generator 
rand_1=tf.random.uniform(shape=(5,300),minval=0,maxval=1)
# using numpy 
rand_2=tf.constant(np.random.random(size=(5,300)))
# notice the difference in the datatypes
rand_1,rand_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.9198024 , 0.9021473 , 0.41526616, ..., 0.5822983 , 0.87424827,
         0.87493646],
        [0.47639966, 0.46232438, 0.02243221, ..., 0.32143807, 0.40111768,
         0.28625727],
        [0.35340595, 0.27560496, 0.40311146, ..., 0.03763556, 0.6741897 ,
         0.6569295 ],
        [0.02055502, 0.901711  , 0.9821774 , ..., 0.9703983 , 0.09900749,
         0.03038132],
        [0.8285135 , 0.3170538 , 0.69191897, ..., 0.7987853 , 0.73130655,
         0.355502  ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float64, numpy=
 array([[0.59802297, 0.24300254, 0.43756827, ..., 0.399046  , 0.08517999,
         0.69811142],
        [0.48274309, 0.89764863, 0.3293635 , ..., 0.86646779, 0.31829585,
         0.82678857],
        [0.23739013, 0.88270689, 0.65409919, ..., 0.50557777, 0.4351621 ,
         0.88981846],
        [0.65419073, 0.76177084, 0.69344922, ..., 0.26107891, 0.96986042,
         0.8101986 ],
        [0.04546

In [ ]:
# Matrix multiplication of the two tensors 
# type 1 # type 2
tf.matmul(rand_1,tf.cast(rand_2,dtype=tf.float32),transpose_b=True) ,tf.cast(rand_1,dtype=tf.float64)@ tf.transpose(rand_2)


(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[76.83791 , 79.065956, 70.551865, 72.23984 , 80.98896 ],
        [72.87721 , 75.51057 , 67.73034 , 68.4623  , 74.34181 ],
        [73.64803 , 80.86321 , 68.74929 , 72.71942 , 78.25747 ],
        [77.77457 , 81.77639 , 75.136856, 72.165886, 78.92928 ],
        [77.37176 , 79.32943 , 72.0336  , 72.70772 , 80.97714 ]],
       dtype=float32)>, <tf.Tensor: shape=(5, 5), dtype=float64, numpy=
 array([[76.83791218, 79.06592496, 70.55182845, 72.2398364 , 80.98896957],
        [72.87724327, 75.5105715 , 67.73032461, 68.46229403, 74.34182167],
        [73.64803718, 80.86321484, 68.74930737, 72.71944889, 78.25748385],
        [77.77461209, 81.77639678, 75.13686614, 72.16589743, 78.92925538],
        [77.37180237, 79.32946797, 72.03363327, 72.70767907, 80.97714835]])>)

In [ ]:
# multiply using the dot product 

tf.tensordot(rand_1,tf.transpose(tf.cast(rand_2,dtype=tf.float32)),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.83791 , 79.065956, 70.551865, 72.23984 , 80.98896 ],
       [72.87721 , 75.51057 , 67.73034 , 68.4623  , 74.34181 ],
       [73.64803 , 80.86321 , 68.74929 , 72.71942 , 78.25747 ],
       [77.77457 , 81.77639 , 75.136856, 72.165886, 78.92928 ],
       [77.37176 , 79.32943 , 72.0336  , 72.70772 , 80.97714 ]],
      dtype=float32)>

In [ ]:
# create a random matric with the given shape 
tf.random.Generator.from_seed(42)
ten_3=tf.random.normal(shape=(224,224,3))
ten_3

In [ ]:
# Find the min and max values in the tensor that has been created 
tf.reduce_max(ten_3),tf.reduce_min(ten_3)

(<tf.Tensor: shape=(), dtype=float32, numpy=4.6342225>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-4.404409>)

In [ ]:
# Create  a random tensor with the given size and then squeeze

ten_4=tf.random.uniform(shape=(1,224,224,3),maxval=500)
tf.squeeze(ten_4)

In [ ]:
rand_ten=tf.constant(np.arange(0,10))
tf.argmax(rand_ten).numpy(),rand_ten

(9,
 <tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>)

In [ ]:
tf.one_hot(rand_ten,depth=tf.size(rand_ten).numpy())

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>